language: rust
os: osx
rust:
  - stable
script:
  - cargo build --verbose --release
  - mv target/release/crlfconv target/release/crlfconv-osx
deploy:
  provider: releases
  skip_cleanup: true
  file: "target/release/crlfconv-osx"
  api_key:
    secure: "LEgNG0DblKoxHdlDgJRp2UaHRCIQDwMgpbXW4PDOsmNhMhB0J5VElDzz59dQssdJqIwkG80fPVNyW08iQJUiZrVqqSfELvcC98X7ZsFG26l8BSyTkUwyzddNUDnT5WWohbQRuLOLc5CjD8/bxMSrgoAwOJgPKUBDKQjdJrjd/LxftwT+aYWffIchGftpFnt7DCbh5c5JuSwcQz2u7dBhiQVXO9iBioFBXUtzZH1PEbY5STjPOSC9HbvBS1oq9N3D28+ML5Ik3cjPsvFv+cixSHwRObOQIuvJNpldeF+x8jw/00d2fyOagmIN8/CZ2gmpysY0pr0j/AXeGahai0vpWdXAyP9g0IR7673dTdg8pawEr1AMTWz+aa5XOT6TSQ42QQnEaeCul4lw2vzCDzgZyQO/vhYzHM9s9ozOS0LybMmDytZHYdLQVITiN4tzR32UcMu0CKCqnAl1x1j5MaCrkSWT84SM+7QcMOjdF0ZtJ4OZ0QPuUrguuIB04l3Io70Zhm7gQKr3DLCjAehlDm8EDEoT0rABzH0U+OoFh6TG9KVRQmnOhwu3oAXjq5ilYk4EpIOkpp36uOat9DdH8kdaciPtcOG8wOBE228UEQVibAO76t1WvSj2P341+PxMQZHzDWOCAqqhmHmrRfyEJ3A0ErSYDfWsF8H657fSWMPO1pk="
  on:
    tags: true