version: 1.0.{build}
skip_tags: false
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CHANNEL: stable
      TARGET: x86_64-pc-windows-gnu
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CHANNEL: stable
      TARGET: i686-pc-windows-gnu

install:
- pwsh: >-
      curl -sSf https://win.rustup.rs/x86_64 -o rustup-init.exe

      .\rustup-init.exe --default-host $env:TARGET --default-toolchain $env:CHANNEL -y

      $env:PATH = "$($env:PATH);$(Join-Path $env:USERPROFILE .cargo/bin)"

      rustc -vV

      cargo -V
build: false
test_script:
  - set PATH=%PATH%;%USERPROFILE%/.cargo/bin
  - cargo build --verbose --release
  - ren target\release\crlfconv.exe crlfconv-%TARGET%.exe
artifacts:
  - path: target/release/crlfconv-%TARGET%.exe
    name: crlfconv-binary
deploy:
  - provider: GitHub
    auth_token:
      secure: "shj27QumlQzHI4tJDnaC+RWZ0Wn6Ovqa5fSjRCczbsAoXOmYVlJJbymhaFt+Ruav"
    artifact: crlfconv-binary
    on:
      APPVEYOR_REPO_TAG: true