version: 1.0.{build}
skip_tags: false
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CHANNEL: stable
      TARGET: i686-unknown-linux-musl
      RUST_HOST: i686-unknown-linux-gnu

install:
- pwsh: >-
      curl -sSf https://sh.rustup.rs -o rustup-init.sh

      sh rustup-init.sh --default-host $env:RUST_HOST --default-toolchain $env:CHANNEL -y

      $env:PATH = "$($env:PATH):$(Join-Path $env:HOME .cargo/bin)"

      rustup target add $env:TARGET

      sudo apt-get update

      sudo apt-get install gcc-multilib -y

      
build: false
test_script:
  - export PATH=$PATH:$HOME/.cargo/bin
  - cargo build --verbose --release --target $TARGET
  - mv target/$TARGET/release/crlfconv target/$TARGET/release/crlfconv-$TARGET
artifacts:
  - path: target/$TARGET/release/crlfconv-*
    name: crlfconv-binary
deploy:
  - provider: GitHub
    auth_token:
      secure: "shj27QumlQzHI4tJDnaC+RWZ0Wn6Ovqa5fSjRCczbsAoXOmYVlJJbymhaFt+Ruav"
    artifact: crlfconv-binary
    on:
      APPVEYOR_REPO_TAG: true