version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-gnu
    - channel: stable
      target: i686-unknown-linux-gnu
    - channel: stable
      target: x86_64-apple-darwin

install:
- pwsh: >-
    curl -sSf https://win.rustup.rs/x86_64 -o rustup-init.exe

    .\rustup-init.exe --default-host $env:TARGET --default-toolchain $env:CHANNEL -y

    $env:PATH = "$($env:PATH);$(Join-Path $env:USERPROFILE .cargo/bin)"

    rustc -vV

    cargo -V
build: false
test_script:
  - set PATH=%PATH%;%USERPROFILE%/.cargo/bin
  - cargo build --verbose --release
artifacts:
  - path: target/release/crlfconv*
    name: crlfconv-binary